name: Auto Translate

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  review:
    name: review
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.INFERENCE_AWS_ROLE_ARN }}
          role-duration-seconds: 1800
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActionsSession-translate
      - name: Run translate
        run: |
          yarn toolkit-md translate --write ./website/docs

          yarn prettier --write ./website/docs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Automated translation updates"
          branch: "automated-translations"
          delete-branch: true
          labels: |
            content/other
          add-paths: |
            website/docs/**/*.md
